### ISSUE TITLE
Doesn't calculate total properly

### ISSUE THREAD

**Issue by chrossystem** [Whelement/CRSH1TTY-public-beta#8]
@localuser-isback 
The subprocesses each track their own codes, so it won't stop after 10,000, but only stop after all of the subprocesses reach 10,000, which will take way longer.

**Comment by localuser-isback** [comment]
interesting, didnt think of that
ill check this out later.

**Comment by localuser-isback** [comment]
should be a easy fix

**Comment by osama248184148184184184** [comment]
test a pr before u merge it :D

**Comment by osama248184148184184184** [comment]
Ubisoft goes Steamworks bye bye, always on DRM

**Comment by chrossystem** [comment]
It shouldn't be too hard. Just make a shared variable or something

**Comment by chrossystem** [comment]
I'm fixing it rn, don't fix it
